#!/usr/bin/env python3
"""Regenerate testfiles/test-index.md from fixture TEST-* headers."""

from __future__ import annotations

import argparse
import difflib
import importlib.util
import sys
from collections import defaultdict
from pathlib import Path

try:
    import tomllib
except ImportError:  # pragma: no cover - Python <3.11 fallback
    import tomli as tomllib  # type: ignore

SCRIPT_PATH = Path(__file__).resolve()
PROJECT_ROOT = SCRIPT_PATH.parents[2]
DEFAULT_ROOT = PROJECT_ROOT / "testfiles"
KIND_ORDER = ["unit", "integration", "stress"]
SECTION_TITLES = {"unit": "Unit", "integration": "Integration", "stress": "Stress"}
REQUIRED_FIELDS = ["TEST-PURPOSE", "TEST-KIND", "TEST-STATUS"]


def _load_header_parser():
    parser_path = PROJECT_ROOT / "testfiles" / "test_header_parser.py"
    spec = importlib.util.spec_from_file_location("codep_test_header_parser", parser_path)
    if spec is None or spec.loader is None:
        raise ImportError(f"cannot load parser from {parser_path}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


PARSER = _load_header_parser()


def _configured_index_path(root: Path | None) -> Path:
    if root is not None:
        return Path(root) / "test-index.md"
    paths_toml = PROJECT_ROOT / ".claude" / "paths.toml"
    try:
        data = tomllib.loads(paths_toml.read_text(encoding="utf-8"))
        rel = data.get("scripts", {}).get("test_index", "testfiles/test-index.md")
    except (OSError, tomllib.TOMLDecodeError):
        rel = "testfiles/test-index.md"
    return PROJECT_ROOT / rel


def _display(value: str | None) -> str:
    if value is None or not value.strip():
        return "—"
    return value.strip().replace("|", "\\|")


def _behavior_value(headers: dict, rel_path: str, baseline: set[str]) -> str:
    behavior = headers.get("TEST-BEHAVIOR", "").strip()
    if behavior:
        return behavior
    exempt = headers.get("TEST-EXEMPT", "").strip()
    if exempt:
        return f"(exempt: {exempt})"
    if rel_path in baseline:
        return "—"
    return ""


def _fixture_record(path: Path, repo_root: Path, baseline: set[str]) -> tuple[dict | None, list[str]]:
    parsed = PARSER.parse_test_kind_headers(path)
    headers = parsed["headers"]
    rel_path = PARSER.repo_relative(path, repo_root)
    errors: list[str] = []

    for field in REQUIRED_FIELDS:
        if not headers.get(field, "").strip():
            line = parsed["first_executable_lineno"] or 1
            errors.append(f"{rel_path}:{line}: missing {field}")

    kind = headers.get("TEST-KIND", "").strip()
    if kind == "stress" and not headers.get("TEST-RENDER-MODES", "").strip():
        line = parsed["line_numbers"].get("TEST-KIND", [1])[0]
        errors.append(f"{rel_path}:{line}: missing TEST-RENDER-MODES for stress fixture")

    behavior = _behavior_value(headers, rel_path, baseline)
    if behavior == "":
        line = parsed["line_numbers"].get("TEST-KIND", [1])[0]
        errors.append(f"{rel_path}:{line}: missing TEST-BEHAVIOR (or .test-behavior-baseline entry)")

    if errors:
        return None, errors

    return {
        "path": rel_path,
        "kind": kind,
        "status": headers.get("TEST-STATUS", "").strip(),
        "purpose": headers.get("TEST-PURPOSE", "").strip(),
        "behavior": behavior,
        "render_modes": headers.get("TEST-RENDER-MODES", "").strip(),
    }, []


def build_index(root: Path | None = None) -> tuple[str, list[str]]:
    fixture_root = Path(root) if root is not None else DEFAULT_ROOT
    baseline = PARSER.read_behavior_baseline(PROJECT_ROOT)
    grouped: dict[str, list[dict]] = defaultdict(list)
    errors: list[str] = []

    for path in PARSER.iter_test_fixtures(fixture_root):
        record, record_errors = _fixture_record(path, PROJECT_ROOT, baseline)
        errors.extend(record_errors)
        if record is None:
            continue
        if record["kind"] not in KIND_ORDER:
            errors.append(f"{record['path']}:1: invalid TEST-KIND {record['kind']!r}")
            continue
        grouped[record["kind"]].append(record)

    if errors:
        return "", errors

    lines = [
        "# Test fixture index (generated — do not edit)",
        "",
        "This file is auto-generated by `.claude/scripts/regenerate_test_index.py` and",
        "verified in CI by `python3 testfiles/run-tests.py --check-test-index --full`.",
        "Edit fixture headers, not this file.",
        "",
    ]

    for kind in KIND_ORDER:
        records = sorted(grouped.get(kind, []), key=lambda item: item["path"])
        lines.append(f"## {SECTION_TITLES[kind]} ({len(records)} fixtures)")
        lines.append("")
        if kind == "stress":
            lines.extend([
                "| Path | Status | Render modes | Behavior | Purpose |",
                "|---|---|---|---|---|",
            ])
            for record in records:
                lines.append(
                    "| {path} | {status} | {render_modes} | {behavior} | {purpose} |".format(
                        path=_display(record["path"]),
                        status=_display(record["status"]),
                        render_modes=_display(record["render_modes"]),
                        behavior=_display(record["behavior"]),
                        purpose=_display(record["purpose"]),
                    )
                )
        else:
            lines.extend([
                "| Path | Status | Behavior | Purpose |",
                "|---|---|---|---|",
            ])
            for record in records:
                lines.append(
                    "| {path} | {status} | {behavior} | {purpose} |".format(
                        path=_display(record["path"]),
                        status=_display(record["status"]),
                        behavior=_display(record["behavior"]),
                        purpose=_display(record["purpose"]),
                    )
                )
        lines.append("")

    return "\n".join(lines).rstrip() + "\n", []


def _diff(expected: str, current: str, index_path: Path) -> str:
    return "".join(
        difflib.unified_diff(
            current.splitlines(keepends=True),
            expected.splitlines(keepends=True),
            fromfile=f"{index_path} (current)",
            tofile=f"{index_path} (generated)",
        )
    )


def regenerate(check: bool = False, root: str | Path | None = None) -> int:
    """Regenerate or check the test index.

    Returns 0 on success/no diff, 1 on check-mode diff, and 2 on fatal parse
    errors. This signature is intentionally importlib-friendly for the runner.
    """

    root_path = Path(root) if root is not None else None
    index_path = _configured_index_path(root_path)
    expected, errors = build_index(root_path)
    if errors:
        for error in errors:
            print(error, file=sys.stderr)
        return 2

    try:
        current = index_path.read_text(encoding="utf-8")
    except FileNotFoundError:
        current = ""

    if current == expected:
        return 0

    if check:
        print(_diff(expected, current, index_path), file=sys.stderr, end="")
        return 1

    index_path.parent.mkdir(parents=True, exist_ok=True)
    index_path.write_text(expected, encoding="utf-8")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if test-index.md is stale; do not write")
    parser.add_argument("--root", default=None, help="fixture root to scan (default: testfiles)")
    args = parser.parse_args(argv)
    return regenerate(check=args.check, root=args.root)


if __name__ == "__main__":
    sys.exit(main())
